# Generated by Django 3.1.3 on 2020-11-05 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201105_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 11, 5, 13, 48, 48, 861028, tzinfo=utc)),
        ),
    ]
