# Generated by Django 3.1.3 on 2020-11-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201105_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tasks', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.projects')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
