# Generated by Django 3.1.3 on 2020-11-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_projects_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
