# Generated by Django 3.1.3 on 2020-11-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201106_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tasks',
        ),
    ]
